# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drydock < Formula
  desc "DryDock is a local GitOps sandbox environment"
  homepage "https://github.com/joaopires/drydock"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.4.0/drydock_Darwin_x86_64.tar.gz"
      sha256 "eaed1bedb498a72220a80c3c7c2ef89151389570b13896578be8bd5464a43b41"

      define_method(:install) do
        bin.install "drydock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.4.0/drydock_Darwin_arm64.tar.gz"
      sha256 "9a642c38e519afd197a45f72625688f96fead4ef40ce7fd907ccfc993315403a"

      define_method(:install) do
        bin.install "drydock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.4.0/drydock_Linux_x86_64.tar.gz"
      sha256 "4d7a106d5e9a7f0e5ce884cab4e6ad2192523b1abe0564cd869ee24f564ea4aa"
      define_method(:install) do
        bin.install "drydock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.4.0/drydock_Linux_arm64.tar.gz"
      sha256 "ae2cf8ba017940287573973f8e3fbaa8d953807911aa8be12fa13e053f4222ce"
      define_method(:install) do
        bin.install "drydock"
      end
    end
  end
end
