# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drydock < Formula
  desc "DryDock is a local GitOps sandbox environment"
  homepage "https://github.com/joaopires/drydock"
  version "0.5.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.5.4/drydock_Darwin_x86_64.tar.gz"
      sha256 "6bfe9af77ef5793d5d2be4e74878c57fc2b120d0cc1fd804b7790b7360021262"

      define_method(:install) do
        bin.install "drydock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.5.4/drydock_Darwin_arm64.tar.gz"
      sha256 "af73f157a2fa58f26bb3c83b64e57782c2cd71c904a160b2752f9dea4d1cb2bd"

      define_method(:install) do
        bin.install "drydock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.5.4/drydock_Linux_x86_64.tar.gz"
      sha256 "72381894168e7997f5096f2355cbd12da7eb3cb748093da05f4bace2978eb7a4"
      define_method(:install) do
        bin.install "drydock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.5.4/drydock_Linux_arm64.tar.gz"
      sha256 "45403b146c506c94115d426ed146bee4d64dd7f637041c23792dcd95b92c4de5"
      define_method(:install) do
        bin.install "drydock"
      end
    end
  end
end
