# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drydock < Formula
  desc "DryDock is a local GitOps sandbox environment"
  homepage "https://github.com/joaopires/drydock"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.6.1/drydock_Darwin_x86_64.tar.gz"
      sha256 "58f2ae9b15d9647e158565748a6710fd2f98acff0bb46f17750b37940449f2c5"

      define_method(:install) do
        bin.install "drydock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.6.1/drydock_Darwin_arm64.tar.gz"
      sha256 "4e048f43cedd2c87509673d2ee008b710dc9137700aee791af9deace93f548dd"

      define_method(:install) do
        bin.install "drydock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.6.1/drydock_Linux_x86_64.tar.gz"
      sha256 "e1850e8bc8b6cefb283b48c0ed938039748db2195f1eb8093091f4affe5f8baa"
      define_method(:install) do
        bin.install "drydock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaopires/homebrew-tap/releases/download/v0.6.1/drydock_Linux_arm64.tar.gz"
      sha256 "f2a36f075ab3ce2dc73b9e5a1d2340110e03cb280523992d1aef0264baaf287b"
      define_method(:install) do
        bin.install "drydock"
      end
    end
  end
end
